### ISSUE TITLE
not sure why?

### ISSUE THREAD

**Issue by WolfLiSteel** [A4Papers/ChatFilter#6]
just want to show this. 
i see internal error and i needed to keep reloading the plugin
- [Thu 12:31:57 ERROR Minecraft] null
org.bukkit.command.CommandException: Unhandled exception executing command 'cf' in plugin ChatFilter v2.0.13
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916)
    at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
    at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
    at net.minecraft.commands.Commands.performCommand(Commands.java:305)
    at net.minecraft.commands.Commands.performCommand(Commands.java:289)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2294)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248)
    at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318)
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311)
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289)
    at net.minecraft.

**Comment by WolfLiSteel** [comment]
[Thu 12:55:55 INFO  ChatFilter] Enabling ChatFilter v2.0.13
! [Thu 12:55:55 WARN  Minecraft] Enabled plugin with unregistered PluginClassLoader ChatFilter v2.0.13
 
- [Thu 12:55:55 ERROR Minecraft] Error occurred while enabling ChatFilter v2.0.13 (Is it up to date?)
java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 13
((f)+(\W|_)*(*)+(\W|_)*(\(|c)+(\W|_)*(k)+(\W|_)*)
             ^
    at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
    at java.base/java.util.regex.Pattern.sequence(Pattern.java:2203)
    at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
    at java.base/java.util.regex.Pattern.group0(Pattern.java:3050)
    at java.base/java.util.regex.Pattern.sequence(Pattern.java:2124)
    at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
    at java.base/java.util.regex.Pattern.group0(Pattern.java:3050)
    at java.base/java.util.regex.Pattern.sequence(Pattern.java:2124)
    at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
    at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
    at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
    at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
    at ChatFilter.jar//a4.papers.chatfilter.chatfilter.shared.regexHandler.LoadFilters.regexCompile(LoadFilters.java:142)
    at ChatFilter.jar//a4.papers.chatfilter.chatfilter.ChatFilter.onEnable(ChatFilter.java:153)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
    at PluginManager.jar//net.lenni0451.spm.utils.PluginUtils.enablePlugin(PluginUtils.java:116)
    at PluginManager.jar//net.lenni0451.spm.commands.subs.Enable_Sub.execute(Enable_Sub.java:42)
    at PluginManager.jar//net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94)
    at PluginManager.jar//net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
    at org.bukkit.comman
  [Thu 12:55:55 INFO  ChatFilter] Disabling ChatFilter v2.0.13

**Comment by A4Papers** [comment]
Did you enter your own regex?

**Comment by WolfLiSteel** [comment]
nope. i dont know how
